package com.alphagraph.api.report;

import com.alphagraph.api.error.NotFoundException;
import io.swagger.v3.oas.annotations.Operation;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;

/** Module 3.6: the Daily AI Report - a once-daily synthesized digest, generated by decision.report.DailyReportScheduler (22:00 IST) and served read-only here. No role restriction beyond a valid JWT. */
@RestController
@RequestMapping("/api/v1/daily-report")
public class DailyReportController {

    private final DailyReportViewService viewService;

    public DailyReportController(DailyReportViewService viewService) {
        this.viewService = viewService;
    }

    @Operation(summary = "Latest daily report")
    @GetMapping
    public DailyReportDto latest() {
        return viewService.latest().orElseThrow(() -> new NotFoundException("No daily report has been generated yet"));
    }

    @Operation(summary = "Daily report for a specific date", description = "ISO date, e.g. 2026-06-01.")
    @GetMapping("/{reportDate}")
    public DailyReportDto byDate(@PathVariable @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate reportDate) {
        return viewService.byDate(reportDate).orElseThrow(() -> new NotFoundException("No daily report for " + reportDate));
    }
}
